export enum AlertCategory {
  DDOS = "DDOS",
  BRUTE_FORCE = "BRUTE_FORCE",
  MALWARE = "MALWARE",
  PHISHING = "PHISHING",
  EXPLOITATION = "EXPLOITATION",
  DATA_EXFILTRATION = "DATA_EXFILTRATION",
  MISCONFIGURATION = "MISCONFIGURATION",
  POLICY_VIOLATION = "POLICY_VIOLATION",
  OTHER = "OTHER",
}