export enum MaturityLevel {
  INITIAL = "INITIAL",
  MANAGED = "MANAGED",
  DEFINED = "DEFINED",
  QUANTITATIVELY_MANAGED = "QUANTITATIVELY_MANAGED",
  OPTIMIZING = "OPTIMIZING",
  UNKNOWN = "UNKNOWN",
}
